### ISSUE TITLE
Error while running espresso test cases more than 150 case failed with an error (Out Of Memory) 

### ISSUE THREAD

**Issue by JeyaChitra997** [JeyaChitra997/shopping#1]
When we have more than 150–200 automation test cases written for our application which takes around 1 to 1.5 hours to run completely. There we can face an issue of OOM (Out Of Memory) error while running test cases.

**Tried solution methods :**

1. Increasing the RAM size
2. Android Test Orchestrator
3. JacocoTestReport

**Increasing the RAM size :** 

 Increased the RAM size heap memory size in android studio but still it showing the out of memory exception while running the test case.

`[04:48:28]: ▸ at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:325)
[04:48:28]: ▸ at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:265)
[04:48:28]: ▸ at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
[04:48:28]: ▸ at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[04:48:28]: ▸ at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[04:48:28]: ▸ at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[04:48:28]: ▸ at java.base/java.lang.Thread.run(Thread.java:829)
[04:56:05]: ▸ com.reimbursify.profile.overview.activity.ActivityInsuranceCardScanTest > onClickBack FAILED
[04:56:05]: ▸ java.lang.OutOfMemoryError: Java heap space
[04:56:05]: ▸ java.lang.IllegalStateException: init() must be called prior to using this method.
[04:56:05]: ▸ at androidx.test.espresso.intent.Checks.checkState(Checks.java:70)
[04:56:05]: ▸ at androidx.test.espresso.intent.Intents.internalRelease(Intents.java:329)
[04:56:05]: ▸ at androidx.test.espresso.intent.Intents.release(Intents.java:137)
[04:56:05]: ▸ at xxx.activity.ActivityInsuranceCardScanTest.afterTest(ActivityInsuranceCardScanTest.java:75)
[04:56:05]: ▸ xxx.activity.ActivityInsuranceCardScanTest > onActivityResult STARTED`

**Android Test Orchestrator :** 

  Implemented the orchestrator test case method. all test cases are running but all test cases are failing.

**Reference Link :** https://medium.com/globant/oom-out-of-memory-error-while-running-espresso-test-cases-power-of-android-test-orchestrator-721ac7012f86

**JacocoTestReport :** 

  Implemented the Jacoco test report while running the test cases. It throwing the out of memory exception while running the test case.

**Reference Link :**
https://about.codecov.io/blog/code-coverage-for-android-development-using-kotlin-jacoco-github-actions-and-codecov/

**Comment by JeyaChitra997** [comment]
If any one find the solution it will help me to resolve this.
